language: node_js
node_js:
- "0.10"
before_script:
  - npm update -q
  - gem install sass
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
install:
  - sudo apt-get install libgif-dev
script: bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/Esri/cedar.git
    - secure: "47d4dbad4593765b23655dbf1bfe5c4bec005606"
